name: ci

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
        with:
          node-version-file: web/.node-version
          pnpm-version: "8.9.2"
          working-directory: web
      - run: pnpm i
      - run: pnpm lint
